baseURL = "https://app-dep-vicmaburrito.vercel.app/"
languageCode = 'es-ES'
title = 'My Portafolio'
theme = "paper"
defaultContentLanguage = "es"

# Number of posts to show in recent posts list (Optional). Defaults to 10.

[build]
publish = "public"

[params]
    # show selector to switch language
    showLanguageSelector = true

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # set a custom favicon (default is a `themeColor` square)
    # favicon = "favicon.ico"

    # set all headings to their default size (depending on browser settings)
    # it's set to `true` by default
    # oneHeadingSize = false
    pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
  twitter = '@ManuelAldaraca'                # twitter.com/YOUR_TWITTER_ID
  github = 'vicmaburrito'                  # github.com/YOUR_GITHUB_ID
  instagram = 'manuelaldaraca'            # instagram.com/YOUR_INSTAGRAM_ID

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/vicmaburrito"

[[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https://www.instagram.com/manuelaldaraca/"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/manuelaldaraca"

# Enable tags.
[taxonomies]
   tag = "tags"

   [languages]
  [languages.es]
    languageName = "Español"
    title = "My Portafolio"
    subtitle = "Building my portafolio"
    keywords = "Manuel Aldaraca Full-Stack Developer"
    copyright = ""
    menuMore = "Mostrar más"
    readMore = "Leer más"
    readOtherPosts = "Leer otros posts"

    [languages.es.params.logo]
      logoText = "vicmaburrito"
      logoHomeLink = "/"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.es.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.es.menu.main]]
        identifier = "faq"
        name = "FAQ"
        url = "/faq"